name: Build and Deploy Docker image to DockerHub

on:
  push:
    branches: [ main ]
jobs:

  test:  
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm ci
      - run: npm run test

  configure:
    needs: [test]
    runs-on: ubuntu-latest

    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::${{secrets.CDK_DEPLOY_ACCOUNT}}:role/github-actions
        aws-region: ${{secrets.CDK_DEPLOY_REGION}}
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  deploy:
    needs: [configure]
    runs-on: ubuntu-latest

    steps:
    - name: deploy
      run: npm run deploy
      env:
        CDK_DEPLOY_REGION: ${{secrets.CDK_DEPLOY_REGION}}
        CDK_DEPLOY_ACCOUNT: ${{secrets.CDK_DEPLOY_ACCOUNT}}
        CDK_DEPLOY_STAGE: prod

    
